automation:
  - id: kodi_play_video_playlist
    alias: "Kodi: Play Video Playlist"
    trigger:
      - platform: time
        at: "20:00:00"  # This is the time you want the playlist to start, for example, 8 PM.
    action:
      - service: media_player.turn_on
        target:
          entity_id: media_player.kodi
      - service: kodi.call_method
        target:
          entity_id: media_player.kodi
        data:
          method: Playlist.Clear
          params:
            playlistid: 1  # Playlist ID for video
      - service: kodi.call_method
        target:
          entity_id: media_player.kodi
        data:
          method: Playlist.Add
          params:
            playlistid: 1  # Playlist ID for video
            item:
              file: "/local/media/playlist.m3u8"  # Replace with the path to your playlist file
      - service: kodi.call_method
        target:
          entity_id: media_player.kodi
        data:
          method: Player.Open
          params:
            item:
              playlistid: 1  # Playlist ID for video
